timezone: Europe/London
lookback_days: 7
max_items_per_section: 10

intent:
  include: >
    Track updates in the Freelancer Management Systems (FMS) space and the wider freelance economy:
    Product & Feature Signals (launches, enhancements, rollouts for sourcing, onboarding, compliance,
    contracting, execution, payments, budget, reporting, integrations, security);
    Strategic Moves (partnerships, integrations, acquisitions, funding, IPOs, expansions);
    Market & Trend Signals (AI automation in FMS platforms, compliance tooling, integrations, low/no-code,
    niche platforms, freelancers as entrepreneurs, APAC growth, market size/valuation reports);
    Regulation & Risk (IR35, HMRC/IRS/EU directives, umbrella company law, worker classification, indemnity,
    platform work directive, payroll compliance);
    Influencer/Analyst Commentary (Matt Mottola, Jon Younger, Barry Matthews, Josh Bersin, executives at Deel/Remote/Upwork/Fiverr,
    Staffing Industry Analysts).
    Prioritize enterprise-relevant signals with verifiable sources (press releases, analyst reports, vendor blogs).
  exclude: >
    Aviation "flight management system" content;
    consumer gig/freelancer.com job ads or project postings;
    generic SaaStr Q&A or advice blogs not tied to FMS;
    generic SMB/HR productivity tips without concrete FMS relevance;
    unrelated engineering/dev updates;
    marketing fluff or lifestyle content without verifiable claim/source.

categories:
  - Product & Feature Signals
  - Strategic Moves
  - Market & Trend Signals
  - Regulation & Risk
  - Influencer & Analyst Commentary
  - Discovery Highlights

scoring:
  keep_threshold: 0.22    # balanced (0.10 was too low, 0.38 too strict)
  weights:
    Product & Feature Signals: 1.20
    Strategic Moves: 1.20
    Market & Trend Signals: 1.00
    Regulation & Risk: 1.10
    Influencer & Analyst Commentary: 0.85
    Discovery Highlights: 0.70

ranking:
  big_vendor_domains:
    - upwork.com
    - fiverr.com
    - deel.com
    - remote.com
    - toptal.com
    - oysterhr.com
    - papayaglobal.com
    - enterprise-times.co.uk
    - kingsbridge.co.uk
    - eversheds-sutherland.com
    - staffingindustry.com
    - open-assembly.com
  funding_words: ["seed","series a","series b","series c","raises","funding","invests","acquires","merger","acquisition","ipo"]
  contract_words: ["wins contract","awarded","framework","msa","tender","rfp","framework agreement","landed client","enterprise deal"]
  reg_words: ["ir35","hmrc","irs","directive","eu","umbrella company","compliance","worker classification","indemnity","platform work directive","legislation","law"]
  launch_words: ["launches","announces","release notes","general availability","integration","changelog","update","rollout","feature","AI-powered"]
  top_k: 10

trends:
  window_weeks: 8
  new_min_sources: 2
  momentum_jump_pct: 60
