include_discovery: true
max_new_feeds_per_run: 60

discovery:
  expand_from_kept_links: true
  max_new_sources_per_week: 5
  min_weeks_to_promote: 2

rss:
  - https://www.producthunt.com/feed
  - https://joshbersin.com/feed/
  - https://feeds.harvardbusiness.org/harvardbusiness/ideacast
  - https://humancloud.substack.com/feed
  - https://www.gov.uk/search/news-and-communications.atom
  - https://www.consilium.europa.eu/en/rss/pressreleases.ashx

domains:
  - worksuite.com
  - worksome.com
  - talentdesk.io
  - yunojuno.com
  - workmarket.com
  - shortl.ist
  - talentdesk.com
  - upwork.com
  - fiverr.com
  - toptal.com
  - usebraintrust.com
  - a.team
  - contra.com
  - malt.com
  - comatch.com
  - gocatalant.com
  - expert360.com
  - talmix.com
  - outvise.com
  - gigged.ai
  - flexingit.com
  - unicorn.io
  - deel.com
  - remote.com
  - oysterhr.com
  - papayaglobal.com
  - velocityglobal.com
  - g-p.com
  - safeguardsglobal.com
  - omnipresent.com
  - pilot.co
  - atlashxm.com
  - rippling.com
  - multiplier.com
  - boundlesshq.com
  - teampayroll.com
  - plane.com
  - remotepad.com
  - shieldgeo.com
  - beeline.com
  - magnitglobal.com
  - allegisglobalsolutions.com
  - pontoonsolutions.com
  - guidantglobal.com
  - randstadsourceright.com
  - tapfin.com
  - prodigysourcing.com
  - brightfieldts.com
  - fieldnation.com
  - sap.com
  - workday.com
  - servicemax.com
  - servicemarketplace.com
  - mbopartners.com
  - cxcglobal.com
  - independently.ai
  - enterprise.alexandermannsolutions.com
  - lawinsider.com
  - littler.com
  - osborneclarke.com
  - eversheds-sutherland.com
  - fragomen.com
  - bakermckenzie.com
  - hfw.com
  - lewissilkin.com
  - staffingindustry.com
  - open-assembly.com
  - unleash.ai
  - shrm.org
  - worktech.com
  - reworked.co
  - sloanreview.mit.edu
  - hbr.org
  - gartner.com
  - forrester.com
  - spendmatters.com
  - zdnet.com
  - techcrunch.com
  - wired.com
  - theinformation.com
  - finance.yahoo.com
  - businesswire.com
  - prnewswire.com
  - globenewswire.com
  - gov.uk
  - legislation.gov.uk
  - irdigital.blog.gov.uk
  - icas.com
  - irs.gov
  - dol.gov
  - osha.gov
  - europa.eu
  - ec.europa.eu
  - europarl.europa.eu
  - consilium.europa.eu
  - oecd.org
  - ilo.org
  - beis.gov.uk
  - op.europa.eu
  - hse.gov.uk
  - ico.org.uk
  - wise.com
  - payoneer.com
  - stripe.com
  - adyen.com
  - checkout.com
  - revolut.com
  - staffinghub.com
  - hrtechconference.com
  - saastr.com
  - websummit.com
  - recfest.com
  - unleash.ai/events
  - dev.to
  - medium.com
  - github.blog
  - producthunt.com
  - stackshare.io
  - freelancer.com
  - peopleperhour.com
  - guru.com
  - 99designs.com
  - designcrowd.com
  - crowdworks.jp
  - lancers.jp
  - werkspot.nl
  - twago.com
  - mckinsey.com
  - bcg.com
  - accenture.com
  - deloitte.com
  - pwc.com
  - ey.com
  - kpmg.com
  - wsj.com
  - ft.com
  - bloomberg.com
  - reuters.com
  - cnbc.com
  - theverge.com
  - protocol.com
  - venturebeat.com
  - axios.com
  - fortune.com
