include_discovery: true
max_new_feeds_per_run: 60

discovery:
  expand_from_kept_links: true
  max_new_sources_per_week: 5
  min_weeks_to_promote: 2

rss:
  # --- Core FMS / freelance platforms ---
  - https://www.deel.com/rss.xml
  - https://remote.com/blog/rss.xml
  - https://www.upwork.com/press/rss
  - https://blog.fiverr.com/feed/
  - https://www.toptal.com/blog.rss
  - https://www.honeybook.com/blog/feed
  - https://yunojuno.com/feed
  - https://worksuite.com/feed
  - https://blog.worksome.com/feed
  - https://www.papayaglobal.com/feed/
  - https://oysterhr.com/blog/rss
  - https://www.malt.com/blog/feed
  - https://contra.com/blog/feed
  - https://blog.usebraintrust.com/rss/
  - https://build.a.team/feed
  - https://gocatalant.com/feed
  - https://expert360.com/feed
  - https://www.talmix.com/feed
  - https://gigged.ai/feed

  # --- EOR / payroll / contractor management ---
  - https://velocityglobal.com/feed/
  - https://www.g-p.com/feed/
  - https://www.omnipresent.com/blog/rss.xml
  - https://www.usemultiplier.com/blog/rss
  - https://boundlesshq.com/feed
  - https://plane.com/blog/rss
  - https://shieldgeo.com/feed

  # --- Workforce tech / VMS ---
  - https://www.beeline.com/feed/
  - https://magnitglobal.com/feed/
  - https://www.guidantglobal.com/rss.xml
  - https://www.randstadsourceright.com/rss.xml
  - https://blog.workday.com/feed
  - https://news.sap.com/feed/

  # --- Analysts / influencers / podcasts ---
  - https://staffingindustry.com/feed/
  - https://joshbersin.com/feed/
  - https://open-assembly.com/feed/
  - https://humancloud.substack.com/feed
  - https://feeds.harvardbusiness.org/harvardbusiness/ideacast
  - https://joshbersin.com/feed/podcast/   # Josh Bersin podcast

  # --- Regulation / policy ---
  - https://www.gov.uk/search/news-and-communications.atom?keywords=IR35
  - https://www.consilium.europa.eu/en/press/press-releases/rss/
  - https://www.irs.gov/newsroom/rss-feed

  # --- Vendor YouTube channels (product demos, changelogs) ---
  - https://www.youtube.com/feeds/videos.xml?channel_id=UCvxGFOnwUBDHHcxuPqhe4CQ  # Upwork
  - https://www.youtube.com/feeds/videos.xml?channel_id=UCQieDTrc3ZeCPPNoJEFbqaQ  # Fiverr
  - https://www.youtube.com/feeds/videos.xml?channel_id=UCPJsrP8zyttajAybEMQBNgA  # Remote
  - https://www.youtube.com/feeds/videos.xml?channel_id=UCNqm_euTHZz3o5OnKhUS-oA  # Toptal
  - https://www.youtube.com/feeds/videos.xml?channel_id=UCYiK-3h2CuggLuPk27myBkg  # YunoJuno
  - https://www.youtube.com/feeds/videos.xml?channel_id=UC-jjSXIt8b_nkBBf60B-xCg  # Deel

  # --- Vendor engineering blogs ---
  - https://tech.yunojuno.com/rss

domains:
  # keep your existing domain list as-is (already comprehensive)
  - worksuite.com
  - worksome.com
  - talentdesk.io
  - yunojuno.com
  - workmarket.com
  - shortl.ist
  - talentdesk.com
  - upwork.com
  - fiverr.com
  - toptal.com
  - usebraintrust.com
  - a.team
  - contra.com
  - malt.com
  - comatch.com
  - gocatalant.com
  - expert360.com
  - talmix.com
  - outvise.com
  - gigged.ai
  - flexingit.com
  - unicorn.io
  - deel.com
  - remote.com
  - oysterhr.com
  - papayaglobal.com
  - velocityglobal.com
  - g-p.com
  - safeguardsglobal.com
  - omnipresent.com
  - pilot.co
  - atlashxm.com
  - rippling.com
  - multiplier.com
  - boundlesshq.com
  - teampayroll.com
  - plane.com
  - remotepad.com
  - shieldgeo.com
  - beeline.com
  - magnitglobal.com
  - allegisglobalsolutions.com
  - pontoonsolutions.com
  - guidantglobal.com
  - randstadsourceright.com
  - tapfin.com
  - prodigysourcing.com
  - brightfieldts.com
  - fieldnation.com
  - sap.com
  - workday.com
  - servicemax.com
  - servicemarketplace.com
  - mbopartners.com
  - cxcglobal.com
  - independently.ai
  - enterprise.alexandermannsolutions.com
  - lawinsider.com
  - osborneclarke.com
  - eversheds-sutherland.com
  - fragomen.com
  - bakermckenzie.com
  - lewissilkin.com
  - staffingindustry.com
  - open-assembly.com
  - unleash.ai
  - shrm.org
  - worktech.com
  - reworked.co
  - sloanreview.mit.edu
  - hbr.org
  - gartner.com
  - forrester.com
  - spendmatters.com
  - zdnet.com
  - techcrunch.com
  - wired.com
  - theinformation.com
  - finance.yahoo.com
  - businesswire.com
  - prnewswire.com
  - globenewswire.com
  - gov.uk
  - legislation.gov.uk
  - irdigital.blog.gov.uk
  - icas.com
  - irs.gov
  - dol.gov
  - osha.gov
  - europa.eu
  - ec.europa.eu
  - europarl.europa.eu
  - consilium.europa.eu
  - oecd.org
  - ilo.org
  - beis.gov.uk
  - op.europa.eu
  - hse.gov.uk
  - ico.org.uk
  - wise.com
  - payoneer.com
  - stripe.com
  - adyen.com
  - checkout.com
  - revolut.com
  - staffinghub.com
  - hrtechconference.com
  - saastr.com
  - websummit.com
  - recfest.com
  - unleash.ai/events
  - producthunt.com
  - stackshare.io
  - malt.es
  - malt.fr
  - malt.de
  - malt.it
  - malt.nl
  - malt.co.uk
  - mckinsey.com
  - bcg.com
  - accenture.com
  - deloitte.com
  - pwc.com
  - ey.com
  - kpmg.com
  - wsj.com
  - ft.com
  - bloomberg.com
  - reuters.com
  - cnbc.com
  - theverge.com
  - protocol.com
  - venturebeat.com
  - axios.com
  - fortune.com
