include_discovery: true
max_new_feeds_per_run: 60

discovery:
  expand_from_kept_links: true
  max_new_sources_per_week: 5
  min_weeks_to_promote: 2

rss:
  # Product discovery
  - https://www.producthunt.com/feed

  # Analysts / podcasts
  - https://joshbersin.com/feed/
  - https://feeds.harvardbusiness.org/harvardbusiness/ideacast
  - https://humancloud.substack.com/feed
  - https://joshbersin.com/feed/podcast/              # Josh Bersin podcast

  # Regulation / policy
  - https://www.gov.uk/search/news-and-communications.atom
  - https://www.consilium.europa.eu/en/rss/pressreleases.ashx
  - https://www.gov.uk/search/news-and-communications.atom?keywords=IR35
  - https://www.consilium.europa.eu/en/press/press-releases/rss/

  # Vendor & competitor YouTube channels
  - https://www.youtube.com/feeds/videos.xml?channel_id=UCvxGFOnwUBDHHcxuPqhe4CQ  # Upwork
  - https://www.youtube.com/feeds/videos.xml?channel_id=UCQieDTrc3ZeCPPNoJEFbqaQ  # Fiverr
  - https://www.youtube.com/feeds/videos.xml?channel_id=UCPJsrP8zyttajAybEMQBNgA  # Remote
  - https://www.youtube.com/feeds/videos.xml?channel_id=UCNqm_euTHZz3o5OnKhUS-oA  # Toptal
  - https://www.youtube.com/feeds/videos.xml?channel_id=UCYiK-3h2CuggLuPk27myBkg  # YunoJuno
  - https://www.youtube.com/feeds/videos.xml?channel_id=UC-jjSXIt8b_nkBBf60B-xCg  # Deel

  # Vendor engineering blog
  - https://tech.yunojuno.com/rss

domains:
  # ——— FMS platforms (core) ———
  - worksuite.com
  - worksome.com
  - talentdesk.io
  - yunojuno.com
  - workmarket.com
  - shortl.ist
  - talentdesk.com

  # ——— Marketplaces / freelance platforms ———
  - upwork.com
  - fiverr.com
  - toptal.com
  - usebraintrust.com
  - a.team
  - contra.com
  - malt.com
  - comatch.com
  - gocatalant.com
  - expert360.com
  - talmix.com
  - outvise.com
  - gigged.ai
  - flexingit.com
  - unicorn.io

  # ——— EOR / Payroll ———
  - deel.com
  - remote.com
  - oysterhr.com
  - papayaglobal.com
  - velocityglobal.com
  - g-p.com
  - safeguardsglobal.com
  - omnipresent.com
  - pilot.co
  - atlashxm.com
  - rippling.com
  - multiplier.com
  - boundlesshq.com
  - teampayroll.com
  - plane.com
  - remotepad.com
  - shieldgeo.com

  # ——— MSPs / VMS ———
  - beeline.com
  - magnitglobal.com
  - allegisglobalsolutions.com
  - pontoonsolutions.com
  - guidantglobal.com
  - randstadsourceright.com
  - tapfin.com
  - prodigysourcing.com
  - brightfieldts.com
  - fieldnation.com
  - sap.com
  - workday.com
  - servicemax.com
  - servicemarketplace.com

  # ——— Compliance, misclassification ———
  - mbopartners.com
  - cxcglobal.com
  - independently.ai
  - enterprise.alexandermannsolutions.com
  - lawinsider.com
  - littler.com
  - osborneclarke.com
  - eversheds-sutherland.com
  - fragomen.com
  - bakermckenzie.com
  - hfw.com
  - lewissilkin.com

  # ——— Analysts, research & media ———
  - staffingindustry.com
  - open-assembly.com
  - unleash.ai
  - shrm.org
  - worktech.com
  - reworked.co
  - sloanreview.mit.edu
  - hbr.org
  - gartner.com
  - forrester.com
  - spendmatters.com
  - zdnet.com
  - techcrunch.com
  - wired.com
  - theinformation.com
  - finance.yahoo.com
  - businesswire.com
  - prnewswire.com
  - globenewswire.com

  # ——— Government & policy ———
  - gov.uk
  - legislation.gov.uk
  - irdigital.blog.gov.uk
  - icas.com
  - irs.gov
  - dol.gov
  - osha.gov
  - europa.eu
  - ec.europa.eu
  - europarl.europa.eu
  - consilium.europa.eu
  - oecd.org
  - ilo.org
  - beis.gov.uk
  - op.europa.eu
  - hse.gov.uk
  - ico.org.uk

  # ——— Payments / Finops ———
  - wise.com
  - payoneer.com
  - stripe.com
  - adyen.com
  - checkout.com
  - revolut.com

  # ——— Event & community hubs ———
  - staffinghub.com
  - hrtechconference.com
  - saastr.com
  - websummit.com
  - recfest.com
  - unleash.ai/events

  # ——— Vendor changelogs / eng blogs (trimmed) ———
  - producthunt.com
  - stackshare.io

  # ——— Regional platforms / niche marketplaces (trimmed) ———
  - malt.es
  - malt.fr
  - malt.de
  - malt.it
  - malt.nl
  - malt.co.uk

  # ——— Finance/analyst houses ———
  - mckinsey.com
  - bcg.com
  - accenture.com
  - deloitte.com
  - pwc.com
  - ey.com
  - kpmg.com

  # ——— General business media ———
  - wsj.com
  - ft.com
  - bloomberg.com
  - reuters.com
  - cnbc.com
  - theverge.com
  - protocol.com
  - venturebeat.com
  - axios.com
  - fortune.com
